// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © marketweek_oficial
//@version=5
indicator("Dynamic Value Zone using EMAs 13/26", overlay=false, timeframe="", timeframe_gaps=true)

ma(source, length, type) =>
    type == "SMA" ? ta.sma(source, length) :
     type == "EMA" ? ta.ema(source, length) :
     type == "SMMA (RMA)" ? ta.rma(source, length) :
     type == "WMA" ? ta.wma(source, length) :
     type == "VWMA" ? ta.vwma(source, length) :
     na

// first ema
show_ma1   = input(true, "Mostrar MA №1", inline="MA #1", display = display.data_window)
ma1_type   = input.string("EMA", "Tipo de MA", inline="MA #1", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma1_source = input(close, "Fonte da MA", inline="MA #1", display = display.data_window)
ma1_length = input.int(13, "Períodos da MA", inline="MA #1", minval=1)
ma1_color  = input(#f6c309, "Cor da MA", inline="MA #1", display = display.data_window)
ma1 = ma(ma1_source, ma1_length, ma1_type)
p1 = plot(show_ma1 ? ma1 : na, color = ma1_color, title="MA №1 (Curta)")

// second ema
show_ma2   = input(true, "Mostrar MA №2", inline="MA #2", display = display.data_window)
ma2_type   = input.string("EMA", "Tipo de MA", inline="MA #2", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma2_source = input(close, "Fonte da MA", inline="MA #2", display = display.data_window)
ma2_length = input.int(26, "Períodos da MA", inline="MA #2", minval=1)
ma2_color  = input(#fb9800, "Cor da MA", inline="MA #2", display = display.data_window)
ma2 = ma(ma2_source, ma2_length, ma2_type)
p2 = plot(show_ma2 ? ma2 : na, color = ma2_color, title="MA №2 (Longa)")

// filling the value area
fill(p1, p2, color=color.new(color.green, 90), title="Área de Valor")

// plotting the price
plot(close, color=color.blue, linewidth=2, title="Linha de Preço")
